### ISSUE TITLE
Vaadin 18  Error: Failed to find the following files:  ./comboBoxConnector-es6.js

### ISSUE THREAD

**Issue by jonathan97h** [vaadin-component-factory/multi-combo-box-flow#16]
I tested this component v.0.4.0 in Vaadin 18.0.5.

If you start the application the following error appears: 

java.lang.IllegalStateException: 

  Failed to find the following files: 
      - ./comboBoxConnector-es6.js
  
  Locations searched were:
      - `/Users/.../vaadin/frontend` in this project
      - `META-INF/frontend` in included JARs

  Please, double check that those files exist. If you use a custom directory for your resource files instead of default `frontend` folder then make sure you it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)

	at com.vaadin.flow.server.frontend.AbstractUpdateImports.getUniqueEs6ImportPaths(AbstractUpdateImports.java:375) ~[flow-server-5.0.2.jar:5.0.2]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.getModuleLines(AbstractUpdateImports.java:388) ~[flow-server-5.0.2.jar:5.0.2]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.collectModules(AbstractUpdateImports.java:301) ~[flow-server-5.0.2.jar:5.0.2]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.run(AbstractUpdateImports.java:110) ~[flow-server-5.0.2.jar:5.0.2]
	at com.vaadin.flow.server.frontend.TaskUpdateImports.execute(TaskUpdateImports.java:376) ~[flow-server-5.0.2.jar:5.0.2]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:634) ~[flow-server-5.0.2.jar:5.0.2]
	at com.vaadin.flow.server.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:471) ~[flow-server-5.0.2.jar:5.0.2]
	at com.vaadin.flow.server.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:381) ~[flow-server-5.0.2.jar:5.0.2]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]

**Comment by Karsten-Buch** [comment]
Same for us in Vaadin 22, it's an impediment for us in the migration from 14 -> 22(23)
